### ISSUE TITLE
Modelagem de Dados

### ISSUE THREAD

**Issue by raissaregis** [IFGO/blog#2]
Fazer a modelagem do banco de dados, contendo as entidades, colulas, relações etc

**Comment by jglcoimbra** [comment]
Segue a imagem com a modelagem da base de dados do BLOG.

![blog_modelagem](https://cloud.githubusercontent.com/assets/11665998/8415688/144202c6-1e77-11e5-911b-edfd87c6b585.png)

Segue o script para criação do banco de dados do BLOG.
Obs.(Criar a DataBase antes das tabelas)

CREATE DATABASE IFG_BLOG; 

CREATE TABLE BLG_USUARIO (
  usuario_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  usuario_nome VARCHAR(255) NOT NULL,
  usuario_email VARCHAR(255) NOT NULL,
  usuario_aniversario DATE NOT NULL,
  usuario_apelido VARCHAR(255) NOT NULL,
  usuario_senha VARCHAR(255) NOT NULL,
  PRIMARY KEY(usuario_id)
);

CREATE TABLE BLG_ARTIGO (
  artigo_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  BLG_USUARIO_usuario_id INTEGER UNSIGNED NOT NULL,
  artigo_titulo VARCHAR(255) NULL,
  artigo_corpo VARCHAR(20000) NULL,
  artigo_datamodificacao DATETIME NULL,
  artigo_datacriacao DATETIME NULL,
  PRIMARY KEY(artigo_id),
  INDEX BLG_ARTIGO_FKIndex1(BLG_USUARIO_usuario_id)
);

CREATE TABLE BLG_COMENTARIO (
  comentario_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  BLG_ARTIGO_artigo_id INTEGER UNSIGNED NOT NULL,
  comentario_autor VARCHAR(255) NOT NULL,
  comentario_data DATETIME NOT NULL,
  comentario_conteudo VARCHAR(1000) NOT NULL,
  PRIMARY KEY(comentario_id),
  INDEX BLG_COMENTARIO_FKIndex1(BLG_ARTIGO_artigo_id)
);
