### ISSUE TITLE
Colocar Banco de Dados Online

### ISSUE THREAD

**Issue by raissaregis** [IFGO/blog#5]
- Baixar projeto do repositório, no netbeans
- Colocar Banco de Dados online ( Raquel)

**Comment by rpa1tera** [comment]
Feito http://brogao.96.lt/
Informações de acesso: https://docs.google.com/document/d/1pBqng4uCxF6SiZXR1ZfCTFLhlI3dNxMlK-OM8roBo0o/edit?usp=sharing
